== Установка и настройка (Windows)

Установите на рабочем компьютере последнюю версию https://www.python.org/downloads/windows[Python] -- для выполнения исходного кода бота.

Настройка бота:

. Запустите файл install_venv.bat, расположенный в основной директории бота, для создания виртуальной среды окружения Python, которая защитит Вашу операционную систему от конфликтов между различными библиотеками Python;
. Приступайте к работе.

=== Что делать, если нельзя установить Python?

Существует способ создания переносимой версии бота, но для этого всё-таки нужен компьютер с Python, но зато только один.

Выполните следующие шаги на отдельном компьютере, предназначенном для сборки приложения:

. Установите последнюю версию https://www.python.org/downloads/windows[Python];
. <<скачать_бота, Скачайте>> бота;
. Запустите файл build_portable.bat, расположенный в основной директории бота;
. Из каталога distr заберите папку бота и распространите её любым удобным способом на компьютерах конечных пользователей.

=== Известные проблемы с установкой

==== Запуск файла install_venv.bat заканчивается неудачно

Вы видите сообщение, что не удалось разрешить зависимости:

[listing,shell]
----
Locking [dev-packages] dependencies...
 Locking...Building requirements...
Resolving dependencies...
Locking Failed!
----

Прежде всего попробуйте перезагрузить компьютер.

Если перезагрузка не помогла, то одной из возможных причин являются ограничения, наложенные администратором сети, вызывающие невозможность проверить SSL сертификат хранилища пакетов Python.

Для решения этой проблемы Вам потребуется компьютер, не связанный указанными ограничениями:

. Установите на нём последнюю версию https://www.python.org/downloads/windows[Python];
. <<скачать_бота, Скачайте>> на него бот;
. Запустите файл install_venv.bat, расположенный в основной директории бота, для создания виртуальной среды окружения Python, которая защитит Вашу операционную систему от конфликтов между различными библиотеками Python;
. В папке бота запустите командную строку и выполните команду:
[source,shell]
pipenv lock --requirements > requirements.txt
. Созданный файл requirements.txt перенесите на целевой (рабочий) компьютер в папку бота;

На рабочем компьютере в папке бота:

. Модифицируйте файл install_venv.bat, закомментировав (добавьте в её начале слово _rem_ и пробел) или удалив строку
[source,shell]
set trustedHostParam=
. Запустите файл install_venv.bat
. Запустите командную строку и выполните команду:
[source,shell]
pipenv run pip install --trusted-host pypi.org --trusted-host pypi.python.org --trusted-host files.pythonhosted.org -r requirements.txt