# Generated by Selenium IDE
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait


class TestEgrnp1:
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_egrnp1(self):
        # Test name: egrn_p1
        # Step # | name | target | value
        # 1 | open | /wps/portal/p/cc_present/EGRN_1 |
        self.driver.get("https://rosreestr.gov.ru/wps/portal/p/cc_present/EGRN_1")
        # 2 | echo | Ввод типа объекта - зу |
        # Ввод типа объекта - зу
        print(str("Ввод типа объекта - зу"))
        # 3 | waitForElementVisible | css=.v-verticallayout-base-egrp-wrapper div:nth-of-type(3) .v-verticallayout-content-wrapper div:nth-of-type(1) div:nth-of-type(1) div:nth-of-type(1) > div:nth-of-type(1) > .v-verticallayout:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(1) input.v-filterselect-input | 30000
        WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR,
                                                                                                   ".v-verticallayout-base-egrp-wrapper div:nth-of-type(3) .v-verticallayout-content-wrapper div:nth-of-type(1) div:nth-of-type(1) div:nth-of-type(1) > div:nth-of-type(1) > .v-verticallayout:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(1) input.v-filterselect-input")))
        # 4 | click | css=.v-verticallayout-base-egrp-wrapper div:nth-of-type(3) .v-verticallayout-content-wrapper div:nth-of-type(1) div:nth-of-type(1) div:nth-of-type(1) > div:nth-of-type(1) > .v-verticallayout:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(1) input.v-filterselect-input |
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".v-verticallayout-base-egrp-wrapper div:nth-of-type(3) .v-verticallayout-content-wrapper div:nth-of-type(1) div:nth-of-type(1) div:nth-of-type(1) > div:nth-of-type(1) > .v-verticallayout:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(1) "
                                 "input.v-filterselect-input").click()
        # 5 | waitForElementEditable | css=.v-verticallayout-base-egrp-wrapper div:nth-of-type(3) .v-verticallayout-content-wrapper div:nth-of-type(1) div:nth-of-type(1) div:nth-of-type(1) > div:nth-of-type(1) > .v-verticallayout:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(1) input.v-filterselect-input | 30000
        WebDriverWait(self.driver, 30000).until(expected_conditions.element_to_be_clickable((By.CSS_SELECTOR,
                                                                                             ".v-verticallayout-base-egrp-wrapper div:nth-of-type(3) .v-verticallayout-content-wrapper div:nth-of-type(1) div:nth-of-type(1) div:nth-of-type(1) > div:nth-of-type(1) > .v-verticallayout:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(1) input.v-filterselect-input")))
        # 6 | type | css=.v-verticallayout-base-egrp-wrapper div:nth-of-type(3) .v-verticallayout-content-wrapper div:nth-of-type(1) div:nth-of-type(1) div:nth-of-type(1) > div:nth-of-type(1) > .v-verticallayout:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(1) input.v-filterselect-input | Земельный участок
        self.driver.find_element(By.CSS_SELECTOR,
                                 ".v-verticallayout-base-egrp-wrapper div:nth-of-type(3) .v-verticallayout-content-wrapper div:nth-of-type(1) div:nth-of-type(1) div:nth-of-type(1) > div:nth-of-type(1) > .v-verticallayout:nth-of-type(1) > div:nth-of-type(1) > div:nth-of-type(1) input.v-filterselect-input") \
            .send_keys("Земельный участок")
        # 7 | waitForElementVisible | xpath=//td[contains(@class,"gwt-MenuItem")]/span[text()='Земельный участок'] | 30000
        WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located(
            (By.XPATH, "//td[contains(@class,\"gwt-MenuItem\")]/span[text()=\'Земельный участок\']")))
        # 8 | click | xpath=//td[contains(@class,"gwt-MenuItem")]/span[text()='Земельный участок'] |
        self.driver.find_element(By.XPATH,
                                 "//td[contains(@class,\"gwt-MenuItem\")]/span[text()=\'Земельный участок\']").click()
        # 9 | echo | Ввод КН |
        # Ввод КН
        print(str("Ввод КН"))
        # 10 | click | css=div:nth-of-type(3) > div > .v-horizontallayout .v-verticallayout input.v-textfield |
        self.driver.find_element(By.CSS_SELECTOR,
                                 "div:nth-of-type(3) > div > .v-horizontallayout .v-verticallayout input.v-textfield").click()
        # 11 | waitForElementEditable | css=div:nth-of-type(3) > div > .v-horizontallayout .v-verticallayout input.v-textfield | 30000
        WebDriverWait(self.driver, 30000).until(expected_conditions.element_to_be_clickable(
            (By.CSS_SELECTOR, "div:nth-of-type(3) > div > .v-horizontallayout .v-verticallayout input.v-textfield")))
        # 12 | type | css=div:nth-of-type(3) > div > .v-horizontallayout .v-verticallayout input.v-textfield | 25:28:030009:29
        self.driver.find_element(By.CSS_SELECTOR,
                                 "div:nth-of-type(3) > div > .v-horizontallayout .v-verticallayout input.v-textfield").send_keys(
            "25:28:030009:29")
        # 13 | echo | Ввод площади |
        # Ввод площади
        print(str("Ввод площади"))
        # 14 | click | xpath=(//div[3]/div//div[@class='v-horizontallayout']//div[@class='v-verticallayout']/following::input)[1] |
        self.driver.find_element(By.XPATH,
                                 "(//div[3]/div//div[@class=\'v-horizontallayout\']//div[@class=\'v-verticallayout\']/following::input)[1]").click()
        # 15 | waitForElementEditable | xpath=(//div[3]/div//div[@class='v-horizontallayout']//div[@class='v-verticallayout']/following::input)[1] | 30000
        WebDriverWait(self.driver, 30000).until(expected_conditions.element_to_be_clickable((By.XPATH,
                                                                                             "(//div[3]/div//div[@class=\'v-horizontallayout\']//div[@class=\'v-verticallayout\']/following::input)[1]")))
        # 16 | type | xpath=(//div[3]/div//div[@class='v-horizontallayout']//div[@class='v-verticallayout']/following::input)[1] | 12345678910
        self.driver.find_element(By.XPATH,
                                 "(//div[3]/div//div[@class=\'v-horizontallayout\']//div[@class=\'v-verticallayout\']/following::input)[1]").send_keys(
            "12345678910")
        # 17 | echo | Ввод единицы измерения -кв. м |
        # Ввод единицы измерения -кв. м
        print(str("Ввод единицы измерения -кв. м"))
        # 18 | click | xpath=(//div[3]/div//div[@class='v-horizontallayout']//div[@class='v-verticallayout']/following::input)[2] |
        self.driver.find_element(By.XPATH,
                                 "(//div[3]/div//div[@class=\'v-horizontallayout\']//div[@class=\'v-verticallayout\']/following::input)[2]").click()
        # 19 | waitForElementEditable | xpath=(//div[3]/div//div[@class='v-horizontallayout']//div[@class='v-verticallayout']/following::input)[2] | 30000
        WebDriverWait(self.driver, 30000).until(expected_conditions.element_to_be_clickable((By.XPATH,
                                                                                             "(//div[3]/div//div[@class=\'v-horizontallayout\']//div[@class=\'v-verticallayout\']/following::input)[2]")))
        # 20 | type | xpath=(//div[3]/div//div[@class='v-horizontallayout']//div[@class='v-verticallayout']/following::input)[2] | Квадратный метр
        self.driver.find_element(By.XPATH,
                                 "(//div[3]/div//div[@class=\'v-horizontallayout\']//div[@class=\'v-verticallayout\']/following::input)[2]").send_keys(
            "Квадратный метр")
        # 21 | waitForElementVisible | xpath=//td[contains(@class,"gwt-MenuItem")]/span[text()='Квадратный метр'] | 30000
        WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located(
            (By.XPATH, "//td[contains(@class,\"gwt-MenuItem\")]/span[text()=\'Квадратный метр\']")))
        # 22 | click | xpath=//td[contains(@class,"gwt-MenuItem")]/span[text()='Квадратный метр'] |
        self.driver.find_element(By.XPATH,
                                 "//td[contains(@class,\"gwt-MenuItem\")]/span[text()=\'Квадратный метр\']").click()
        # 23 | echo | Ввод субъекта РФ |
        # Ввод субъекта РФ
        print(str("Ввод субъекта РФ"))
        # 24 | click | xpath=(//div[3]/div//div[@class='v-horizontallayout']//div[@class='v-verticallayout']/following::input)[3] |
        self.driver.find_element(By.XPATH,
                                 "(//div[3]/div//div[@class=\'v-horizontallayout\']//div[@class=\'v-verticallayout\']/following::input)[3]").click()
        # 25 | waitForElementEditable | xpath=(//div[3]/div//div[@class='v-horizontallayout']//div[@class='v-verticallayout']/following::input)[3] | 30000
        WebDriverWait(self.driver, 30000).until(expected_conditions.element_to_be_clickable((By.XPATH,
                                                                                             "(//div[3]/div//div[@class=\'v-horizontallayout\']//div[@class=\'v-verticallayout\']/following::input)[3]")))
        # 26 | type | xpath=(//div[3]/div//div[@class='v-horizontallayout']//div[@class='v-verticallayout']/following::input)[3] | Приморский край
        self.driver.find_element(By.XPATH,
                                 "(//div[3]/div//div[@class=\'v-horizontallayout\']//div[@class=\'v-verticallayout\']/following::input)[3]").send_keys(
            "Приморский край")
        # 27 | waitForElementVisible | xpath=//td[contains(@class,"gwt-MenuItem")]/span[contains(text(),'Приморский край')] | 30000
        WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located(
            (By.XPATH, "//td[contains(@class,\"gwt-MenuItem\")]/span[contains(text(),\'Приморский край\')]")))
        # 28 | click | xpath=//td[contains(@class,"gwt-MenuItem")]/span[contains(text(),'Приморский край')] |
        self.driver.find_element(By.XPATH,
                                 "//td[contains(@class,\"gwt-MenuItem\")]/span[contains(text(),\'Приморский край\')]").click()
        # 29 | echo | Ввод района |
        # Ввод района
        print(str("Ввод района"))
        # 30 | click | xpath=(//div[3]/div//div[@class='v-horizontallayout']//div[@class='v-verticallayout']/following::input)[4] |
        self.driver.find_element(By.XPATH,
                                 "(//div[3]/div//div[@class=\'v-horizontallayout\']//div[@class=\'v-verticallayout\']/following::input)[4]").click()
        # 31 | waitForElementEditable | xpath=(//div[3]/div//div[@class='v-horizontallayout']//div[@class='v-verticallayout']/following::input)[4] | 30000
        WebDriverWait(self.driver, 30000).until(expected_conditions.element_to_be_clickable((By.XPATH,
                                                                                             "(//div[3]/div//div[@class=\'v-horizontallayout\']//div[@class=\'v-verticallayout\']/following::input)[4]")))
        # 32 | type | xpath=(//div[3]/div//div[@class='v-horizontallayout']//div[@class='v-verticallayout']/following::input)[4] | Владивосток
        self.driver.find_element(By.XPATH,
                                 "(//div[3]/div//div[@class=\'v-horizontallayout\']//div[@class=\'v-verticallayout\']/following::input)[4]").send_keys(
            "Владивосток")
        # 33 | waitForElementVisible | xpath=//td[contains(@class,"gwt-MenuItem")]/span[contains(text(),'Владивосток')] | 30000
        WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located(
            (By.XPATH, "//td[contains(@class,\"gwt-MenuItem\")]/span[contains(text(),\'Владивосток\')]")))
        # 34 | click | xpath=//td[contains(@class,"gwt-MenuItem")]/span[contains(text(),'Владивосток')] |
        self.driver.find_element(By.XPATH,
                                 "//td[contains(@class,\"gwt-MenuItem\")]/span[contains(text(),\'Владивосток\')]").click()
        # 35 | echo | Сведения о пользователе+код ВРУЧНУЮ |
        # Сведения о пользователе+код ВРУЧНУЮ
        print(str("Сведения о пользователе+код ВРУЧНУЮ"))
        # 36 | waitForElementVisible | xpath=//span[contains(text(),'Перейти к сведениям о заявителе')] | 30000
        WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located(
            (By.XPATH, "//span[contains(text(),\'Перейти к сведениям о заявителе\')]")))
        # 37 | click | xpath=//span[contains(text(),'Перейти к сведениям о заявителе')] |
        self.driver.find_element(By.XPATH, "//span[contains(text(),\'Перейти к сведениям о заявителе\')]").click()
        # 38 | echo | Страница со сведениями о заявителе |
        # Страница со сведениями о заявителе
        print(str("Страница со сведениями о заявителе"))
        # 39 | storeValue | css=div:nth-of-type(3) > div > .v-verticallayout > div > div:nth-of-type(1) > div > .v-horizontallayout .v-verticallayout input.v-textfield | PersonSurName
        self.vars["PersonSurName"] = self.driver.find_element(By.CSS_SELECTOR,
                                                              "div:nth-of-type(3) > div > .v-verticallayout > div > div:nth-of-type(1) > div > .v-horizontallayout .v-verticallayout input.v-textfield").get_attribute(
            "value")
        # 40 | waitForElementVisible | xpath=//span[contains(text(),'Перейти к прилагаемым к запросу документам')] | 30000
        WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located(
            (By.XPATH, "//span[contains(text(),\'Перейти к прилагаемым к запросу документам\')]")))
        # 41 | click | xpath=//span[contains(text(),'Перейти к прилагаемым к запросу документам')] |
        self.driver.find_element(By.XPATH,
                                 "//span[contains(text(),\'Перейти к прилагаемым к запросу документам\')]").click()
        # 42 | echo | Страница с документами |
        # Страница с документами
        print(str("Страница с документами"))
        # 43 | waitForElementVisible | xpath=//span[contains(text(),'Перейти к проверке данных')] | 30000
        WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located(
            (By.XPATH, "//span[contains(text(),\'Перейти к проверке данных\')]")))
        # 44 | click | xpath=//span[contains(text(),'Перейти к проверке данных')] |
        self.driver.find_element(By.XPATH, "//span[contains(text(),\'Перейти к проверке данных\')]").click()
        # 45 | echo | Подписать запрос |
        # Подписать запрос
        print(str("Подписать запрос"))
        # 46 | waitForElementVisible | xpath=//span[contains(text(),'Подписать и отправить запрос')] | 30000
        WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located(
            (By.XPATH, "//span[contains(text(),\'Подписать и отправить запрос\')]")))
        # 47 | click | xpath=//span[contains(text(),'Подписать и отправить запрос')] |
        self.driver.find_element(By.XPATH, "//span[contains(text(),\'Подписать и отправить запрос\')]").click()
        # 48 | waitForElementVisible | xpath=//div[contains(@class,'CertificateListDialog')] | 30000
        WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located(
            (By.XPATH, "//div[contains(@class,\'CertificateListDialog\')]")))
        # 49 | click | xpath=//div[contains(@class,'CertificateListDialog')]//td[contains(@class,"subject")][contains(text(),${PersonSurName})] |
        self.driver.find_element(By.XPATH,
                                 "//div[contains(@class,\'CertificateListDialog\')]//td[contains(@class,\"subject\")][contains(text(),self.vars[\"; PersonSurName; \"])]").click()
        # 50 | click | xpath=//div[contains(@class,'CertificateListDialog')]//button[contains(text(),'Подписать')] |
        self.driver.find_element(By.XPATH,
                                 "//div[contains(@class,\'CertificateListDialog\')]//button[contains(text(),\'Подписать\')]").click()
        # 51 | echo | Записать результат |
        # Записать результат
        print(str("Записать результат"))
        # 52 | storeText | css=b | order_num
        self.vars["order_num"] = self.driver.find_element(By.CSS_SELECTOR, "b").text
        # 53 | storeText | css=b | order_code
        self.vars["order_code"] = self.driver.find_element(By.CSS_SELECTOR, "b").text
        # 54 | echo | Повторить запрос |
        # Повторить запрос
        print(str("Повторить запрос"))
        # 55 | waitForElementVisible | xpath=//span[contains(text(),'Сформировать еще один запрос')] | 30000
        WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located(
            (By.XPATH, "//span[contains(text(),\'Сформировать еще один запрос\')]")))
        # 56 | click | xpath=//span[contains(text(),'Сформировать еще один запрос')] |
        self.driver.find_element(By.XPATH, "//span[contains(text(),\'Сформировать еще один запрос\')]").click()
        # 57 | echo | Если произошла ошибка синхронизации |
        # Если произошла ошибка синхронизации
        print(str("Если произошла ошибка синхронизации"))
        # 58 | if | document.evaluate( "count(//*[text()='Out of sync'])", document, null, XPathResult.ANY_TYPE, null ).numberValue>0 |
        if self.driver.execute_script(
                "return (document.evaluate( \"count(//*[text()=\'Out of sync\'])\", document, null, XPathResult.ANY_TYPE, null ).numberValue>0)"):
            # 59 | click | xpath=//u[contains(text(),'click here')] |
            self.driver.find_element(By.XPATH, "//u[contains(text(),\'click here\')]").click()
            # 60 | end |  |
